apiVersion: v1
kind: Secret
metadata:
  name: oz-finance-gitlab-registry
  namespace: {{ .Values.app.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}