apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.app.name }}
  name: mysql-svc
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql
