apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.app.name }}
  name: php-svc
  namespace: {{ .Values.app.name }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: app
