apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.app.name }}
  name: pma-svc
  namespace: {{ .Values.app.name }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
  selector:
    app: pma
