apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.app.name }}
  name: redis-svc
  namespace: {{ .Values.app.name }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
