apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.app.name }}
  name: redis
  namespace: {{ .Values.app.name }}
  labels:
    app: redis
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        # Redis container
        - name: redis
          image: "redis:alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
